//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariHesap.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisID { get; set; }
        public int UrunID { get; set; }
        public int UrunAdet { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<System.DateTime> SatisDate { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
